// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvidaf2UqkJfjGq959WhTLYlcnnsrbifw',
    appId: '1:3649482686:web:809e679db39678f344d3ef',
    messagingSenderId: '3649482686',
    projectId: 'first-app-afd78',
    authDomain: 'first-app-afd78.firebaseapp.com',
    storageBucket: 'first-app-afd78.firebasestorage.app',
    measurementId: 'G-5CB8CW4WDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwGdeLGAYGdAJGeeiZL2swIRZBZBRAdw8',
    appId: '1:3649482686:android:358ccf0d2347e03544d3ef',
    messagingSenderId: '3649482686',
    projectId: 'first-app-afd78',
    storageBucket: 'first-app-afd78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZT4t1KF1FG_stDlvM1mE7W96RkjteAM',
    appId: '1:3649482686:ios:312cb843a95d64fe44d3ef',
    messagingSenderId: '3649482686',
    projectId: 'first-app-afd78',
    storageBucket: 'first-app-afd78.firebasestorage.app',
    iosClientId: '3649482686-8h2ckoa2svrbnvkvt282georvl89e9fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdZT4t1KF1FG_stDlvM1mE7W96RkjteAM',
    appId: '1:3649482686:ios:312cb843a95d64fe44d3ef',
    messagingSenderId: '3649482686',
    projectId: 'first-app-afd78',
    storageBucket: 'first-app-afd78.firebasestorage.app',
    iosClientId: '3649482686-8h2ckoa2svrbnvkvt282georvl89e9fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvidaf2UqkJfjGq959WhTLYlcnnsrbifw',
    appId: '1:3649482686:web:a913c322d2a0bf9344d3ef',
    messagingSenderId: '3649482686',
    projectId: 'first-app-afd78',
    authDomain: 'first-app-afd78.firebaseapp.com',
    storageBucket: 'first-app-afd78.firebasestorage.app',
    measurementId: 'G-1WZG1ZGYM4',
  );
}
